server:
  port: 9981

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    schema: ly-server
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.schema}?useSSL=false&characterEncoding=utf-8
    username: root
    password:
    initialize: false
    continue-on-error: true
  jooq:
      sql-dialect: mysql
  data:
    mongodb:
      uri: mongodb://localhost:27017/ly-server

logging.level.org.jooq: DEBUG